stages:
- prepare
- build
- publish

prepare docs:
  stage: prepare
  image: docker:latest
  script:
  - ./prepare-build.sh
  only:
  - master
  artifacts:
    expire_in: 2 days
    paths:
    - workspace/docs

build doc:
  stage: build
  image: squidfunk/mkdocs-material:latest
  script:
  - ln -s workspace/docs /docs
  - build
  only:
  - master
  dependencies:
  - prepare docs
  artifacts:
    expire_in: 2 days
    paths:
    - workspace/docs/site

build additional assets:
  stage: build
  script:
  - ./build_other_assets.sh
  only:
  - master
  dependencies:
  - build doc
  artifacts:
    expire_in: 2 days
    paths:
    - workspace/docs/site

publish container:
  stage: publish
  script:
  - docker build -t flamingo-docs .
  only:
  - master
  dependencies:
  - build additional assets