stages:
- prepare
- build
- publish

prepare docs:
  stage: prepare
  script:
  - ./prepare-build.sh
  only:
  - master
  artifacts:
    expire_in: 2 days
    paths:
    - workspace/docs

build doc:
  stage: build
  image: squidfunk/mkdocs-material:latest
  script:
  - build
  only:
  - master
  dependencies:
  - prepare docs


publish container:
  stage: publish
  script:
  - docker build -t flamingo-docs .
  only:
  - master
  dependencies:
  - build doc