stages:
- prepare
- build

prepare docs:
  stage: prepare
  script:
  - cd ./prepare-build.sh
  only:
  - master
  artifacts:
    expire_in: 2 days
    paths:
    - workspace/docs
build:
  stage: build
  image: squidfunk/mkdocs-material:latest
  script:
  - build
  only:
  - master
  dependencies:
  - prepare docs