site_name: Flamingo Documentations
extra:
  logo: assets/flamingo-icon.png
  social:
    - type: 'github'
      link: 'https://github.com/i-love-flamingo'
    - type: 'twitter'
      link: 'https://twitter.com/aoepeople'
extra_css:
  - stylesheets/ci.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - extra
  - footnotes
  - abbr
use_directory_urls: false
theme:
  name: 'material'
  favicon: assets/flamingo-small-icon.png
#  custom_dir: 'theme'
  logo: assets/flamingo-small-icon.png

